export namespace GameResultFan {

	export let gameResultFanTable = {
		hustyle0: "平胡",
		huFanNum0: "0",
		hustyle1: "夹边吊",
		huFanNum1: "1",
		hustyle2: "飘胡",
		huFanNum2: "2",
		hustyle3: "七对",
		huFanNum3: "3",
		hustyle4: "宝中宝",
		huFanNum4: "4",
		hustyle5: "飘中飘",
		huFanNum5: "5",
		hustyle6: "宝七小",
		huFanNum6: "6",
		hustyle7: "红中翻倍",
		huFanNum7: "1",
		hustyle8: "对宝",
		huFanNum8: "3",
		hustyle9: "摸宝",
		huFanNum9: "2",
		hustyle10: "点炮",
		huFanNum10: "0",
		hustyle11: "自摸",
		huFanNum11: "1",
		hustyle12: "点黑炮",
		huFanNum12: "2",
		hustyle13: "庄",
		huFanNum13: "1",
		hustyle14: "听牌",
		huFanNum14: "0",
		hustyle15: "未听牌",
		huFanNum15: "0",
	}	
}