const {ccclass, property} = cc._decorator;

let opcodeDefine = []
let opcodeReverse = []

let setOpcode = function(name, code){
    opcodeDefine[name] = code
    opcodeReverse[code] = name
}

setOpcode("mahjong_cb_login_req", 7300)
setOpcode("mahjong_bc_login_ack", 7301)
setOpcode("mahjong_cb_join_table_req", 7302)
setOpcode("mahjong_bc_join_table_ack", 7303)
setOpcode("mahjong_cb_leave_table_req", 7304)
setOpcode("mahjong_bc_leave_table_ack", 7305)
setOpcode("mahjong_bc_ply_join_not", 7306)
setOpcode("mahjong_bc_ply_leave_not", 7307)
setOpcode("mahjong_cb_ready_req", 7308)
setOpcode("mahjong_bc_ready_not", 7309)
setOpcode("mahjong_bc_change_table_req", 7310)
setOpcode("mahjong_cb_chat_req", 7311)
setOpcode("mahjong_bc_chat_not", 7312)
setOpcode("mahjong_cb_change_table_req", 7313)
setOpcode("mahjong_cb_visit_table_req", 7314)
setOpcode("mahjong_cb_get_online_award_req", 7315)
setOpcode("mahjong_bc_get_online_award_ack", 7316)
setOpcode("mahjong_cb_ply_place_not", 7317)
setOpcode("mahjong_bc_update_ply_data_not", 7318)
setOpcode("mahjong_bc_cli_timer_not",7319)
setOpcode("mahjong_bc_message_not", 7320)
setOpcode("mahjong_bc_create_table_ack", 7322)
setOpcode("mahjong_cb_get_table_list_req", 7323)
setOpcode("mahjong_bc_get_table_list_ack", 7324)
setOpcode("mahjong_cb_give_gift_req", 7325)
setOpcode("mahjong_bc_give_gift_ack", 7326)
setOpcode("mahjong_bc_give_gift_not", 7327)
setOpcode("mahjong_cb_get_match_data_req", 7328)
setOpcode("mahjong_bc_get_match_data_ack", 7329)
setOpcode("mahjong_cb_apply_match_req", 7330)
setOpcode("mahjong_bc_apply_match_ack", 7331)
setOpcode("mahjong_cb_reset_match_req", 7332)
setOpcode("mahjong_bc_reset_match_ack", 7333)
setOpcode("mahjong_cb_get_table_list_req2", 7334)
setOpcode("mahjong_bc_get_table_list_ack2", 7335)
setOpcode("mahjong_cb_kickout_req", 7336)
setOpcode("mahjong_bc_kickout_ack", 7337)
setOpcode("mahjong_cb_send_prop_req", 7338)
setOpcode("mahjong_bc_send_prop_ack", 7339)
setOpcode("mahjong_bc_send_prop_not", 7340)
setOpcode("mahjong_cb_get_assist_info_data_req", 7341)
setOpcode("mahjong_bc_get_assist_info_data_ack", 7342)
setOpcode("mahjong_bc_integal_condition_noti", 7343)
setOpcode("mahjong_bc_coupon_not", 7344)
setOpcode("mahjong_br_need_send_robot_not", 7345)
setOpcode("mahjong_bc_common_message_not", 7346)
setOpcode("mahjong_bc_below_admission_limit_tip_not", 7347)
setOpcode("mahjong_bc_recharge_tip_not", 7348)
setOpcode("mahjong_bc_calc_player_round_count_not", 7349)
setOpcode("mahjong_bc_round_award_items_not", 7350)
setOpcode("mahjong_bc_player_round_not", 7351)
setOpcode("mahjong_cb_get_round_award_req", 7352)
setOpcode("mahjong_bc_get_round_award_ack", 7353)
setOpcode("mahjong_bc_award_type_not", 7354)
setOpcode("mahjong_cb_get_task_system_req", 7356)
setOpcode("mahjong_bc_get_task_system_ack", 7357)
setOpcode("mahjong_cb_get_task_award_req", 7358)
setOpcode("mahjong_bc_get_task_award_ack", 7359)
setOpcode("mahjong_bc_ready_ack",7383)

setOpcode("mahjong_jxmj_banker_dice_not", 4010)
setOpcode("mahjong_jxmj_dice_not", 4011)
setOpcode("mahjong_jxmj_playcard_req", 4012)
setOpcode("mahjong_jxmj_playcard_ack", 4013)
setOpcode("mahjong_jxmj_changecard_not", 4014)
setOpcode("mahjong_jxmj_gameresult_not", 4015)
setOpcode("mahjong_jxmj_completedata_req", 4016)
setOpcode("mahjong_jxmj_completedata_not", 4017)
setOpcode("mahjong_jxmj_operate_not", 4018)
setOpcode("mahjong_jxmj_animate_ok_req", 4019)
setOpcode("mahjong_jxmj_svr_dizhu_not", 4020)
setOpcode("mahjong_jxmj_Cli_Auto_Req", 4021)
setOpcode("mahjong_jxmj_Svr_Auto_Not", 4022)
setOpcode("mahjong_jxmj_Cli_TingType_req", 4023)
setOpcode("mahjong_jxmj_gc_clienttimer_not", 4024)
setOpcode("mahjong_jxmj_svr_taifei_not", 4025)
setOpcode("mahjong_jxmj_gc_expression_not", 4026)
setOpcode("mahjong_jxmj_userdata_not", 4028)
setOpcode("mahjong_jxmj_tingfan_not", 4029)
setOpcode("mahjong_jxmj_visi_compdata_not", 4030)
setOpcode("mahjong_jxmj_visi_compdata_req", 4031)
setOpcode("mahjong_jxmj_tingcards_not", 4032)
setOpcode("mahjong_jxmj_kaibao_not", 4033)
setOpcode("mahjong_jxmj_seat_dice_not", 4034)
setOpcode("mahjong_jxmj_private_room_result_not", 4035)
setOpcode("mahjong_jxmj_rount_count_not", 4036)
setOpcode("mahjong_jxmj_get_mj_private_room_result_req", 4037)
setOpcode("mahjong_jxmj_get_mj_private_room_result_ack", 4038)
setOpcode("mahjong_jxmj_pause_game_not", 4039)
setOpcode("mahjong_jxmj_continue_banker_not", 4040)
setOpcode("mahjong_jxmj_hu_card_data_not", 4041)
setOpcode("mahjong_jxmj_dingpiao_req", 4042)
setOpcode("mahjong_jxmj_dingpiao_rsp", 4043)
setOpcode("mahjong_jxmj_dingpiao_not", 4044)
setOpcode("mahjong_jxmj_magic_emoji_req", 4045)
setOpcode("mahjong_jxmj_magic_emoji_noti", 4046)
setOpcode("mahjong_cg_get_redpackets_award_req", 4047)
setOpcode("mahjong_gc_get_redpackets_award_ack", 4048)
setOpcode("mahjong_gc_update_player_tokenmoney_not", 4049)
setOpcode("mahjong_cg_get_redpackets_88yuan_award_req",4050)
setOpcode("mahjong_gc_get_redpackets_88yuan_award_ack",4051)
setOpcode("mahjong_bc_specify_item_update_not", 21285)

console.log(opcodeDefine)

export default function opcodeConfig(obj : String | Number) {
    
    if (typeof obj == "string")
        return opcodeDefine[obj as string]
    else if (typeof obj == "number")
        return opcodeReverse[obj as number]
   
    return null        
}
