const {ccclass, property} = cc._decorator;

let opcodeDefine = []
let opcodeReverse = []

let setOpcode = function(name, code){
    opcodeDefine[name] = code
    opcodeReverse[code] = name
}

setOpcode("mahjong_cb_login_req", 7300)
setOpcode("mahjong_bc_login_ack", 7301)
setOpcode("mahjong_cb_join_table_req", 7302)
setOpcode("mahjong_bc_join_table_ack", 7303)
setOpcode("mahjong_cb_leave_table_req", 7304)
setOpcode("mahjong_bc_leave_table_ack", 7305)
setOpcode("mahjong_bc_ply_join_not", 7306)
setOpcode("mahjong_bc_ply_leave_not", 7307)
setOpcode("mahjong_cb_ready_req", 7308)
setOpcode("mahjong_bc_ready_not", 7309)
setOpcode("mahjong_bc_change_table_req", 7310)
setOpcode("mahjong_cb_chat_req", 7311)
setOpcode("mahjong_bc_chat_not", 7312)
setOpcode("mahjong_cb_change_table_req", 7313)
setOpcode("mahjong_cb_visit_table_req", 7314)
setOpcode("mahjong_cb_get_online_award_req", 7315)
setOpcode("mahjong_bc_get_online_award_ack", 7316)
setOpcode("mahjong_cb_ply_place_not", 7317)
setOpcode("mahjong_bc_update_ply_data_not", 7318)
setOpcode("mahjong_bc_cli_timer_not",7319)
setOpcode("mahjong_bc_message_not", 7320)
setOpcode("mahjong_bc_create_table_ack", 7322)
setOpcode("mahjong_cb_get_table_list_req", 7323)
setOpcode("mahjong_bc_get_table_list_ack", 7324)
setOpcode("mahjong_cb_give_gift_req", 7325)
setOpcode("mahjong_bc_give_gift_ack", 7326)
setOpcode("mahjong_bc_give_gift_not", 7327)
setOpcode("mahjong_cb_get_match_data_req", 7328)
setOpcode("mahjong_bc_get_match_data_ack", 7329)
setOpcode("mahjong_cb_apply_match_req", 7330)
setOpcode("mahjong_bc_apply_match_ack", 7331)
setOpcode("mahjong_cb_reset_match_req", 7332)
setOpcode("mahjong_bc_reset_match_ack", 7333)
setOpcode("mahjong_cb_get_table_list_req2", 7334)
setOpcode("mahjong_bc_get_table_list_ack2", 7335)
setOpcode("mahjong_cb_kickout_req", 7336)
setOpcode("mahjong_bc_kickout_ack", 7337)
setOpcode("mahjong_cb_send_prop_req", 7338)
setOpcode("mahjong_bc_send_prop_ack", 7339)
setOpcode("mahjong_bc_send_prop_not", 7340)
setOpcode("mahjong_cb_get_assist_info_data_req", 7341)
setOpcode("mahjong_bc_get_assist_info_data_ack", 7342)
setOpcode("mahjong_bc_integal_condition_noti", 7343)
setOpcode("mahjong_bc_coupon_not", 7344)
setOpcode("mahjong_br_need_send_robot_not", 7345)
setOpcode("mahjong_bc_common_message_not", 7346)
setOpcode("mahjong_bc_below_admission_limit_tip_not", 7347)
setOpcode("mahjong_bc_recharge_tip_not", 7348)
setOpcode("mahjong_bc_calc_player_round_count_not", 7349)
setOpcode("mahjong_bc_round_award_items_not", 7350)
setOpcode("mahjong_bc_player_round_not", 7351)
setOpcode("mahjong_cb_get_round_award_req", 7352)
setOpcode("mahjong_bc_get_round_award_ack", 7353)
setOpcode("mahjong_bc_award_type_not", 7354)
setOpcode("mahjong_cb_get_task_system_req", 7356)
setOpcode("mahjong_bc_get_task_system_ack", 7357)
setOpcode("mahjong_cb_get_task_award_req", 7358)
setOpcode("mahjong_bc_get_task_award_ack", 7359)
setOpcode("mahjong_bc_ready_ack",7383)

setOpcode("mahjong_gdmj_banker_dice_not", 3970)
setOpcode("mahjong_gdmj_dice_not", 3971)
setOpcode("mahjong_gdmj_playcard_req", 3972)
setOpcode("mahjong_gdmj_playcard_ack", 3973)
setOpcode("mahjong_gdmj_changecard_not", 3974)
setOpcode("mahjong_gdmj_gameresult_not", 3975)
setOpcode("mahjong_gdmj_completedata_req", 3976)
setOpcode("mahjong_gdmj_completedata_not", 3977)
setOpcode("mahjong_gdmj_operate_not", 3978)
setOpcode("mahjong_gdmj_animate_ok_req", 3979)
setOpcode("mahjong_gdmj_svr_dizhu_not", 3980)
setOpcode("mahjong_gdmj_Cli_Auto_Req", 3981)
setOpcode("mahjong_gdmj_Svr_Auto_Not", 3982)
setOpcode("mahjong_gdmj_Cli_TingType_req", 3983)
setOpcode("mahjong_gdmj_gc_clienttimer_not", 3984)
setOpcode("mahjong_gdmj_svr_taifei_not", 3985)
setOpcode("mahjong_gdmj_gc_expression_not", 3986)
setOpcode("mahjong_gdmj_userdata_not", 3988)
setOpcode("mahjong_gdmj_tingfan_not", 3989)
setOpcode("mahjong_gdmj_mapai_not", 3993)
setOpcode("mahjong_gdmj_jph_dice_not", 4004)
setOpcode("mahjong_gdmj_jph_wind_not", 4005)
setOpcode("mahjong_gdmj_jph_gameresult_not", 4006)
setOpcode("mahjong_gdmj_jph_completedata_not", 4007)
setOpcode("mahjong_cg_get_redpackets_award_req", 3998)
setOpcode("mahjong_gc_get_redpackets_award_ack", 3999)
setOpcode("mahjong_gc_update_player_tokenmoney_not", 4000)
setOpcode("mahjong_cg_get_redpackets_88yuan_award_req",4001)
setOpcode("mahjong_gc_get_redpackets_88yuan_award_ack",4002)
setOpcode("mahjong_bc_specify_item_update_not", 21285)

console.log(opcodeDefine)

export default function opcodeConfig(obj : String | Number) {
    
    if (typeof obj == "string")
        return opcodeDefine[obj as string]
    else if (typeof obj == "number")
        return opcodeReverse[obj as number]
   
    return null        
}
