export namespace AudioConfig {

	export let audio_sounds_table = {}
	audio_sounds_table['sound'] = {}
	audio_sounds_table["sound"]["bg_music"] = "sounds/yxbg"

	audio_sounds_table["sound"]["audio_clock"] = "sounds/clock"
	audio_sounds_table["sound"]["audio_ready"] = "sounds/ready"
	audio_sounds_table["sound"]["audio_dianpao"] = "sounds/dianpao"
	audio_sounds_table["sound"]["audio_huang"] = "sounds/huang"
	audio_sounds_table["sound"]["audio_dice"] = "sounds/dice"
	audio_sounds_table["sound"]["audio_throw"] = "sounds/throw"
	audio_sounds_table["sound"]["audio_select_group"] = "sounds/select_group"
	audio_sounds_table["sound"]["audio_card_hover"] = "sounds/card_hover"
	audio_sounds_table["sound"]["audio_down"] = "sounds/down"
	audio_sounds_table["sound"]["audio_duijukaishi"] = "sounds/duijukaishi"
	audio_sounds_table["sound"]["audio_menu"] = "sounds/menu"
	
	
	audio_sounds_table["sound"]["audio_player_enter"] = "sounds/other_player_enter"
	
	audio_sounds_table["sound"]["audio_player_leave"] = "sounds/other_player_leave"
	
	
	audio_sounds_table["sound"]["audio_chat_0"] = "sounds/dialogue/chat_0"
	audio_sounds_table["sound"]["audio_chat_1"] = "sounds/dialogue/chat_1"
	audio_sounds_table["sound"]["audio_chat_2"] = "sounds/dialogue/chat_2"
	audio_sounds_table["sound"]["audio_chat_3"] = "sounds/dialogue/chat_3"
	audio_sounds_table["sound"]["audio_chat_4"] = "sounds/dialogue/chat_4"
	
	audio_sounds_table["sound"]["audio_win"] = "sounds/Win"
	audio_sounds_table["sound"]["audio_lose"] = "sounds/Lost"
	audio_sounds_table["sound"]["audio_double"] = "sounds/double"
	audio_sounds_table["sound"]["audio_double_voice"] = "sounds/double1"
	audio_sounds_table["sound"]["audio_baopai"] = "sounds/baopai"
	
	audio_sounds_table["sound"]["audio_hu_woman"] = "sounds/PuTongHua/woman/woman_hu"
	audio_sounds_table["sound"]["audio_zimo_woman"] = "sounds/PuTongHua/woman/woman_zimo"
	
	audio_sounds_table["sound"]["audio_hu_man"] = "sounds/PuTongHua/man/man_hu"
	audio_sounds_table["sound"]["audio_zimo_man"] = "sounds/PuTongHua/man/man_zimo"
	
	
	audio_sounds_table["sound"]["audio_buhua_woman"] = "sounds/PuTongHua/woman/woman_buhua"
	audio_sounds_table["sound"]["audio_card_1_woman"] = "sounds/PuTongHua/woman/woman1"
	audio_sounds_table["sound"]["audio_card_2_woman"] = "sounds/PuTongHua/woman/woman2"
	audio_sounds_table["sound"]["audio_card_3_woman"] = "sounds/PuTongHua/woman/woman3"
	audio_sounds_table["sound"]["audio_card_4_woman"] = "sounds/PuTongHua/woman/woman4"
	audio_sounds_table["sound"]["audio_card_5_woman"] = "sounds/PuTongHua/woman/woman5"
	audio_sounds_table["sound"]["audio_card_6_woman"] = "sounds/PuTongHua/woman/woman6"
	audio_sounds_table["sound"]["audio_card_7_woman"] = "sounds/PuTongHua/woman/woman7"
	audio_sounds_table["sound"]["audio_card_8_woman"] = "sounds/PuTongHua/woman/woman8"
	audio_sounds_table["sound"]["audio_card_9_woman"] = "sounds/PuTongHua/woman/woman9"
	audio_sounds_table["sound"]["audio_card_11_woman"] = "sounds/PuTongHua/woman/woman11"
	audio_sounds_table["sound"]["audio_card_12_woman"] = "sounds/PuTongHua/woman/woman12"
	audio_sounds_table["sound"]["audio_card_13_woman"] = "sounds/PuTongHua/woman/woman13"
	audio_sounds_table["sound"]["audio_card_14_woman"] = "sounds/PuTongHua/woman/woman14"
	audio_sounds_table["sound"]["audio_card_15_woman"] = "sounds/PuTongHua/woman/woman15"
	audio_sounds_table["sound"]["audio_card_16_woman"] = "sounds/PuTongHua/woman/woman16"
	audio_sounds_table["sound"]["audio_card_17_woman"] = "sounds/PuTongHua/woman/woman17"
	audio_sounds_table["sound"]["audio_card_18_woman"] = "sounds/PuTongHua/woman/woman18"
	audio_sounds_table["sound"]["audio_card_19_woman"] = "sounds/PuTongHua/woman/woman19"
	audio_sounds_table["sound"]["audio_card_21_woman"] = "sounds/PuTongHua/woman/woman21"
	audio_sounds_table["sound"]["audio_card_22_woman"] = "sounds/PuTongHua/woman/woman22"
	audio_sounds_table["sound"]["audio_card_23_woman"] = "sounds/PuTongHua/woman/woman23"
	audio_sounds_table["sound"]["audio_card_24_woman"] = "sounds/PuTongHua/woman/woman24"
	audio_sounds_table["sound"]["audio_card_25_woman"] = "sounds/PuTongHua/woman/woman25"
	audio_sounds_table["sound"]["audio_card_26_woman"] = "sounds/PuTongHua/woman/woman26"
	audio_sounds_table["sound"]["audio_card_27_woman"] = "sounds/PuTongHua/woman/woman27"
	audio_sounds_table["sound"]["audio_card_28_woman"] = "sounds/PuTongHua/woman/woman28"
	audio_sounds_table["sound"]["audio_card_29_woman"] = "sounds/PuTongHua/woman/woman29"
	audio_sounds_table["sound"]["audio_card_31_woman"] = "sounds/PuTongHua/woman/woman31"
	audio_sounds_table["sound"]["audio_card_32_woman"] = "sounds/PuTongHua/woman/woman32"
	audio_sounds_table["sound"]["audio_card_33_woman"] = "sounds/PuTongHua/woman/woman33"
	audio_sounds_table["sound"]["audio_card_34_woman"] = "sounds/PuTongHua/woman/woman34"
	audio_sounds_table["sound"]["audio_card_35_woman"] = "sounds/PuTongHua/woman/woman35"
	audio_sounds_table["sound"]["audio_card_36_woman"] = "sounds/PuTongHua/woman/woman36"
	audio_sounds_table["sound"]["audio_card_37_woman"] = "sounds/PuTongHua/woman/woman37"
	audio_sounds_table["sound"]["audio_CHIPAI_woman"] = "sounds/PuTongHua/woman/woman_chi"
	audio_sounds_table["sound"]["audio_PENGPAI_woman"] = "sounds/PuTongHua/woman/woman_peng"
	audio_sounds_table["sound"]["audio_GANGPAI_woman"] = "sounds/PuTongHua/woman/woman_gang"
	audio_sounds_table["sound"]["audio_TINGPAI_woman"] = "sounds/PuTongHua/woman/woman_ting"
	
	
	audio_sounds_table["sound"]["audio_buhua_man"] = "sounds/PuTongHua/man/man_buhua"
	audio_sounds_table["sound"]["audio_card_1_man"] = "sounds/PuTongHua/man/man1"
	audio_sounds_table["sound"]["audio_card_2_man"] = "sounds/PuTongHua/man/man2"
	audio_sounds_table["sound"]["audio_card_3_man"] = "sounds/PuTongHua/man/man3"
	audio_sounds_table["sound"]["audio_card_4_man"] = "sounds/PuTongHua/man/man4"
	audio_sounds_table["sound"]["audio_card_5_man"] = "sounds/PuTongHua/man/man5"
	audio_sounds_table["sound"]["audio_card_6_man"] = "sounds/PuTongHua/man/man6"
	audio_sounds_table["sound"]["audio_card_7_man"] = "sounds/PuTongHua/man/man7"
	audio_sounds_table["sound"]["audio_card_8_man"] = "sounds/PuTongHua/man/man8"
	audio_sounds_table["sound"]["audio_card_9_man"] = "sounds/PuTongHua/man/man9"	
	audio_sounds_table["sound"]["audio_card_11_man"] = "sounds/PuTongHua/man/man11"
	audio_sounds_table["sound"]["audio_card_12_man"] = "sounds/PuTongHua/man/man12"
	audio_sounds_table["sound"]["audio_card_13_man"] = "sounds/PuTongHua/man/man13"
	audio_sounds_table["sound"]["audio_card_14_man"] = "sounds/PuTongHua/man/man14"
	audio_sounds_table["sound"]["audio_card_15_man"] = "sounds/PuTongHua/man/man15"
	audio_sounds_table["sound"]["audio_card_16_man"] = "sounds/PuTongHua/man/man16"
	audio_sounds_table["sound"]["audio_card_17_man"] = "sounds/PuTongHua/man/man17"
	audio_sounds_table["sound"]["audio_card_18_man"] = "sounds/PuTongHua/man/man18"
	audio_sounds_table["sound"]["audio_card_19_man"] = "sounds/PuTongHua/man/man19"
	audio_sounds_table["sound"]["audio_card_21_man"] = "sounds/PuTongHua/man/man21"
	audio_sounds_table["sound"]["audio_card_22_man"] = "sounds/PuTongHua/man/man22"
	audio_sounds_table["sound"]["audio_card_23_man"] = "sounds/PuTongHua/man/man23"
	audio_sounds_table["sound"]["audio_card_24_man"] = "sounds/PuTongHua/man/man24"
	audio_sounds_table["sound"]["audio_card_25_man"] = "sounds/PuTongHua/man/man25"
	audio_sounds_table["sound"]["audio_card_26_man"] = "sounds/PuTongHua/man/man26"
	audio_sounds_table["sound"]["audio_card_27_man"] = "sounds/PuTongHua/man/man27"
	audio_sounds_table["sound"]["audio_card_28_man"] = "sounds/PuTongHua/man/man28"
	audio_sounds_table["sound"]["audio_card_29_man"] = "sounds/PuTongHua/man/man29"
	audio_sounds_table["sound"]["audio_card_31_man"] = "sounds/PuTongHua/man/man31"
	audio_sounds_table["sound"]["audio_card_32_man"] = "sounds/PuTongHua/man/man32"
	audio_sounds_table["sound"]["audio_card_33_man"] = "sounds/PuTongHua/man/man33"
	audio_sounds_table["sound"]["audio_card_34_man"] = "sounds/PuTongHua/man/man34"
	audio_sounds_table["sound"]["audio_card_35_man"] = "sounds/PuTongHua/man/man35"
	audio_sounds_table["sound"]["audio_card_36_man"] = "sounds/PuTongHua/man/man36"
	audio_sounds_table["sound"]["audio_card_37_man"] = "sounds/PuTongHua/man/man37"
	audio_sounds_table["sound"]["audio_CHIPAI_man"] = "sounds/PuTongHua/man/man_chi"
	audio_sounds_table["sound"]["audio_PENGPAI_man"] = "sounds/PuTongHua/man/man_peng"
	audio_sounds_table["sound"]["audio_GANGPAI_man"] = "sounds/PuTongHua/man/man_gang"
	audio_sounds_table["sound"]["audio_TINGPAI_man"] = "sounds/PuTongHua/man/man_ting"
	
}